name: Generate RSS Feeds

on:
  schedule:
    - cron: '0 * * * *'  # A cada hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    strategy:
      matrix:
        channels:
          - channel_id: "UCO6axYvGFekWJjmSdbHo-8Q"
            filename: "celozaga.xml"
          - channel_id: "UClgqiSfCPt-HJ3SrF3PNSNA"
            filename: "celospiritcrossing.xml"
          - channel_id: "UCFWAzRf9YU6j0k7zuka9Drw"
            filename: "celototopia.xml"
          - channel_id: "UCUiBYLILjv5QU-LZOZhx2ow"
            filename: "celopartystars.xml"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requirements
        run: pip install beautifulsoup4 requests

      - name: Generate RSS Feed for ${{ matrix.channels.filename }}
        run: python generate_rss.py ${{ matrix.channels.channel_id }} ${{ matrix.channels.filename }}

      - name: Commit RSS Feeds
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase origin main
          git add *.xml
          git commit -m "Update RSS feeds" || echo "No changes to commit"
          git push
